name: Convert markdown to html and deploy to S3

on:
  push:
    branches:
      - main

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install markdown

    - name: Run conversion script
      run: python convert_markdown_recipes_to_html.py

    - name: Run script to generate index.html
      run: python generate_index_html.py

    - name: Commit and push the HTML files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git add recipes/*
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Automated conversion of markdown recipes to HTML'
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Sync S3 bucket
      run: |
        aws s3 sync . s3://ajyfood.com \
          --content-type text/html \
          --exclude "*" \
          --include "*.html" \
          --include "favicon.ico" \
          --include "recipes/*" \
          --delete
